services:
  - type: web
    name: math-ocr
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      chmod +x tesseract-linux/tesseract
    startCommand: uvicorn server:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
